/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.util.ArrayList;

/**
 *
 * @author tarde
 */
public class Logueo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Logueo.class.getName());

    /**
     * Creates new form Logeo
     */
    public Logueo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtexto = new javax.swing.JTextArea();
        j8 = new javax.swing.JButton();
        j9 = new javax.swing.JButton();
        j7 = new javax.swing.JButton();
        j5 = new javax.swing.JButton();
        j6 = new javax.swing.JButton();
        j3 = new javax.swing.JButton();
        j4 = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        j0 = new javax.swing.JButton();
        j1 = new javax.swing.JButton();
        jsuma = new javax.swing.JButton();
        jresta = new javax.swing.JButton();
        jreiniciar = new javax.swing.JButton();
        jdivision = new javax.swing.JButton();
        jmultiplicacion = new javax.swing.JButton();
        jresultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtexto.setColumns(20);
        jtexto.setRows(5);
        jScrollPane1.setViewportView(jtexto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 262, 51));

        j8.setText("8");
        j8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j8MouseClicked(evt);
            }
        });
        getContentPane().add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 64, 46, 47));

        j9.setText("9");
        j9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j9MouseClicked(evt);
            }
        });
        getContentPane().add(j9, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 64, 46, 47));

        j7.setText("7");
        j7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j7MouseClicked(evt);
            }
        });
        getContentPane().add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 64, 46, 47));

        j5.setText("5");
        j5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j5MouseClicked(evt);
            }
        });
        getContentPane().add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 117, 46, 47));

        j6.setText("6");
        j6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j6MouseClicked(evt);
            }
        });
        getContentPane().add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 117, 46, 47));

        j3.setText("3");
        j3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j3MouseClicked(evt);
            }
        });
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        getContentPane().add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 170, 46, 47));

        j4.setText("4");
        j4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j4MouseClicked(evt);
            }
        });
        getContentPane().add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 117, 46, 47));

        j2.setText("2");
        j2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2MouseClicked(evt);
            }
        });
        getContentPane().add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 170, 46, 47));

        j0.setText("0");
        j0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j0MouseClicked(evt);
            }
        });
        getContentPane().add(j0, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 223, 46, 47));

        j1.setText("1");
        j1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j1MouseClicked(evt);
            }
        });
        getContentPane().add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 170, 46, 47));

        jsuma.setText("+");
        jsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsumaActionPerformed(evt);
            }
        });
        getContentPane().add(jsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 223, 46, 47));

        jresta.setText("-");
        jresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrestaActionPerformed(evt);
            }
        });
        getContentPane().add(jresta, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 223, 46, 47));

        jreiniciar.setText("C");
        jreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jreiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 64, 46, 47));

        jdivision.setText("/");
        jdivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdivisionActionPerformed(evt);
            }
        });
        getContentPane().add(jdivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 117, 46, 47));

        jmultiplicacion.setText("*");
        jmultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmultiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(jmultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 170, 46, 47));

        jresultado.setText("=");
        jresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresultadoActionPerformed(evt);
            }
        });
        getContentPane().add(jresultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 223, 46, 47));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j3ActionPerformed

    private void j9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j9MouseClicked
        // TODO add your handling code here:
        this.jtexto.setText(this.jtexto.getText() + 9);
    }//GEN-LAST:event_j9MouseClicked

    private void j8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j8MouseClicked
        // TODO add your handling code here:
        this.jtexto.setText(this.jtexto.getText() + 8);

    }//GEN-LAST:event_j8MouseClicked

    private void j7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j7MouseClicked
        this.jtexto.setText(this.jtexto.getText() + 7);
        // TODO add your handling code here:
    }//GEN-LAST:event_j7MouseClicked

    private void j6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j6MouseClicked
        this.jtexto.setText(this.jtexto.getText() + 6);
    }//GEN-LAST:event_j6MouseClicked

    private void j5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j5MouseClicked
        this.jtexto.setText(this.jtexto.getText() + 5);
    }//GEN-LAST:event_j5MouseClicked

    private void j4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j4MouseClicked
        this.jtexto.setText(this.jtexto.getText() + 4);
        // TODO add your handling code here:
    }//GEN-LAST:event_j4MouseClicked

    private void j3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MouseClicked
        this.jtexto.setText(this.jtexto.getText() + 3);
        // TODO add your handling code here:
    }//GEN-LAST:event_j3MouseClicked

    private void j2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2MouseClicked
        this.jtexto.setText(this.jtexto.getText() + 2);
        // TODO add your handling code here:
    }//GEN-LAST:event_j2MouseClicked

    private void j1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseClicked
        this.jtexto.setText(this.jtexto.getText() + 1);
        // TODO add your handling code here:
    }//GEN-LAST:event_j1MouseClicked

    private void j0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j0MouseClicked
        this.jtexto.setText(this.jtexto.getText() + 0);
    }//GEN-LAST:event_j0MouseClicked

    private void jreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreiniciarActionPerformed
        this.jtexto.setText("");
    }//GEN-LAST:event_jreiniciarActionPerformed

    private void jdivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdivisionActionPerformed
        this.jtexto.setText(this.jtexto.getText() + "/");
    }//GEN-LAST:event_jdivisionActionPerformed

    private void jmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmultiplicacionActionPerformed
        this.jtexto.setText(this.jtexto.getText() + "*");
    }//GEN-LAST:event_jmultiplicacionActionPerformed

    private void jresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresultadoActionPerformed
        String a = "";
        String n[];
        ArrayList<String> al = new ArrayList<String>();
        n = this.jtexto.getText().split("");
        for (int i = 0; i < n.length; i++) {
            al.add(n[i]);
        }
        this.jtexto.setText("");
        for (String string : al) {

            if (string.equals("+")) {
                a = sumaCalculadora(al);
            }
            if (string.equals("*")) {
                a = multiplicacionCacluladora(al);
            }
            if (string.equals("/")) {
                a = divisionCacluladora(al);
            }
            if (string.equals("-")) {
                a = restaCacluladora(al);
            }
        }
        this.jtexto.setText(a);


    }//GEN-LAST:event_jresultadoActionPerformed

    private void jrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrestaActionPerformed
        this.jtexto.setText(this.jtexto.getText() + "-");
    }//GEN-LAST:event_jrestaActionPerformed

    private void jsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsumaActionPerformed
        this.jtexto.setText(this.jtexto.getText() + "+");
    }//GEN-LAST:event_jsumaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Logueo().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton j0;
    private javax.swing.JButton j1;
    private javax.swing.JButton j2;
    private javax.swing.JButton j3;
    private javax.swing.JButton j4;
    private javax.swing.JButton j5;
    private javax.swing.JButton j6;
    private javax.swing.JButton j7;
    private javax.swing.JButton j8;
    private javax.swing.JButton j9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jdivision;
    private javax.swing.JButton jmultiplicacion;
    private javax.swing.JButton jreiniciar;
    private javax.swing.JButton jresta;
    private javax.swing.JButton jresultado;
    private javax.swing.JButton jsuma;
    private javax.swing.JTextArea jtexto;
    // End of variables declaration//GEN-END:variables

    private String sumaCalculadora(ArrayList<String> al) {
        String n1 = "";
        String n2 = "";
        int a = 0;
        boolean operando = false;
        for (String string : al) {
            if (string.equals("+")) {
                operando = true;
            }
            if (operando == false) {
                n1 += string;
            } else {
                n2 += string;
            }
        }
        a = Integer.parseInt(n1) + Integer.parseInt(n2);
        return Integer.toString(a);
    }

    private String restaCacluladora(ArrayList<String> al) {
        String n1 = "";
        String n2 = "";
        int a = 0;
        boolean operando = false;
        for (String string : al) {
            if (string.equals("-")) {
                operando = true;
            } else {
                if (operando == false) {
                    n1 += string;
                } else {
                    n2 += string;
                }
            }

        }
        int num1 = Integer.parseInt(n1);
        int num2 = Integer.parseInt(n2);
        a = num1 - num2;
        return Integer.toString(a);
    }

    private String divisionCacluladora(ArrayList<String> al) {
        String n1 = "";
        String n2 = "";
        double a = 0;
        boolean operando = false;
        for (String string : al) {
            if (string.equals("/")) {
                operando = true;
            }else{
                
            
            if (operando == false) {
                n1 += string;
            } else {
                n2 += string;
            }
            }

        }
        a = Double.parseDouble(n1) / Double.parseDouble(n2);
        return Double.toString(a);
    }

    private String multiplicacionCacluladora(ArrayList<String> al) {
        String n1 = "";
        String n2 = "";
        int a = 0;
        boolean operando = false;
        for (String string : al) {
            if (string.equals("*")) {
                operando = true;
            } else {
                if (operando == false) {
                    n1 += string;
                } else {
                    n2 += string;
                }
            }

        }
        int num1 = Integer.parseInt(n1);
        int num2 = Integer.parseInt(n2);
        a = num1 * num2;
        return Integer.toString(a);
    }
}
